name: Bug report
title: "[BUG] "
description: Report a bug of Shizuku
labels: ["pending triage"]

body:
  - type: markdown
    attributes:
      value: |
        Please report bugs of Shizuku itself.\
        **Reports not meet the requirements will be immediately closed**.
  - type: textarea
    id: id_0
    attributes:
      label: |
        Information
      description: |
        - Shizuku version:
        - Mode: [adb, root]
        - Android version:
        - Device: (optional)
    validations:
      required: true
  - type: textarea
    id: id_1
    attributes:
      label: |
        Logs
      description: |
        Related **full logcat**.
    validations:
      required: false
  - type: textarea
    id: id_2
    attributes:
      label: |
        Describe the bug
      description: |
        A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: id_3
    attributes:
      label: |
        Additional context:
      description: |
        Add any other context about the problem here.
    validations:
      required: false