#!/system/bin/sh
BASEDIR=$(dirname "$0")
DEX="$BASEDIR"/bsh_shizuku.dex

if [ ! -f "$DEX" ]; then
  echo "Cannot find $DEX, please check the tutorial in Shizuku app"
  exit 1
fi

# Replace "PKG" with the application id of your terminal app
export BSH_APPLICATION_ID="PKG"
/system/bin/app_process -Djava.class.path="$DEX" /system/bin --nice-name=bsh rikka.shizuku.shell.ShizukuShellLoader "$@"
