name: Build Release CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
        
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Generate keystore
        run: keytool -genkey -alias a -dname "CN=CN" -storepass passwd -keypass passwd -keystore android.keystore

      - name: Create sign config
        run: echo -e "KEYSTORE_FILE=$(pwd)/android.keystore\nKEYSTORE_PASSWORD=passwd\nKEYSTORE_ALIAS=a\nKEYSTORE_ALIAS_PASSWORD=passwd" >> signing.properties

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew :manager:assembleRelease
