name: Build Release CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
        
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Generate keystore
        run: keytool -genkey -alias a -dname "CN=CN" -storepass passwd -keypass passwd -keystore android.keystore

      - name: Create sign config
        run: echo -e "KEYSTORE_FILE=$(pwd)/android.keystore\nKEYSTORE_PASSWORD=passwd\nKEYSTORE_ALIAS=a\nKEYSTORE_ALIAS_PASSWORD=passwd" >> signing.properties

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew :manager:assembleRelease

      - name: Check apk
        env:
          BUILD_TOOLS_VERSION: 30.0.3
        run: |
          export APK_PATH=$(find ./manager/build/outputs/apk/release/ -maxdepth 1 -name *.apk)
          export PATH=$PATH:$ANDROID_SDK_ROOT/build-tools/$BUILD_TOOLS_VERSION
          aapt2 dump badging $APK_PATH
          aapt2 dump permissions $APK_PATH
          aapt2 dump strings $APK_PATH
          aapt2 dump resources $APK_PATH
          aapt2 dump configurations $APK_PATH

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: shizuku_apk_${{ github.sha }}
          path: manager/build/outputs/apk/release/*.apk

      - name: Upload mappings
        uses: actions/upload-artifact@v2
        with:
          name: shizuku_mappings_${{ github.sha }}
          path: manager/build/outputs/mapping/release
